kubevirt/common-instancetypes

- image/Dockerfile
- scripts/check.sh
We need the current working directory to be marked as safe within the git config before running `git diff`.
This is required when running the script within a container image or prow job otherwise the following error is shown:
```
$ COMMON_INSTANCETYPES_CRI=docker make check
./scripts/cri.sh  "./scripts/check.sh"
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
```
A previous attempt to fix this in the Dockerfile is removed as the assumed path of the repo changes between local docker runs and prow jobs.
Fixes # …
> check: Add pwd as safe git directory

- scripts/cri.sh
Required by podman, otherwise we cannot run scripts within the mount.
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
Fixes #
```release-note
NONE
```
> cri: Use private unshared label for bind mount

- README.md
- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/server/micro/kustomization.yaml
- common-instancetypes/instancetypes/sizes/micro/kustomization.yaml
- common-instancetypes/instancetypes/sizes/micro/micro.yaml
This should be suitable for use with CirrOS [1] and other minimal test
OSes used by KubeVirt CI.
[1] https://github.com/cirros-dev/cirros/issues/53
Fixes #
```release-note
A new `micro` size has been introduced and used by the existing `server` family of instance types.
```
> Introduce and use a micro size server instancetype

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/legacy/highperformance/base/highperformance.yaml
A recent change to KubeVirt [1][2] has essentially disabled the use of dedicatedCPUPlacement as we have no way of expressing the required resource requirements through instance types at present.
Until this is corrected all requests to create instance types with this attribute will be rejected. This change drops the use of this attribute until this is resolved.
[1] https://github.com/kubevirt/kubevirt/pull/8886 
[2] https://github.com/kubevirt/kubevirt/issues/8867
Fixes #
```release-note
The use of `dedicatedCPUPlacement` has been dropped …
```
> Drop use of dedicatedCPUPlacement

- .github/workflows/release.yaml
/cc @0xFelix 
This change introduces an additional step to the release workflow, creating a PR within the `kubevirt/ssp-operator` project importing the updated bundles of cluster resources. This was previously force merged and ran below:
https://github.com/kubevirt/common-instancetypes/actions/runs/3904777026
https://github.com/kubevirt/ssp-operator/pull/481
I've pulled the commit out and into a PR for a formal review. In future it would be nice to somehow support testing these workflows through tools like [`act`](https://github.com/nektos/act) but I couldn't get it to work for me this time around.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
> github: Add release update task for SSP operator

- scripts/check.sh
`git config --global --add` will always add a new line to `safe.directory` when called so check if it's actually required before calling.
Fixes #
```release-note
NONE
```
> check: Check if safe.directory is already configured before adding an entry

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/hyperscale/cx/base/cx.yaml
Instance types using dedicatedCPUPlacement have recently started to be rejected by virt-api [1] as we currently have no way of expressing the required resource requests within an instance type.
dedicatedCPUPlacement is also a requirement when using guestMappingPassthrough and as such this also needs to be removed from our shipped instance types ahead of a similar check being introduced [2] in virt-api.
[1] https://github.com/kubevirt/kubevirt/pull/8886 
[2] https://github.com/kubevirt/kubevirt/pull/9105
Fixes #
```release-note
The use of …
```
> CX: Remove `guestMappingPassthrough`

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/hyperscale/cx/base/cx.yaml
- common-instancetypes/instancetypes/hyperscale/m/base/m.yaml
- common-instancetypes/instancetypes/legacy/highperformance/base/highperformance.yaml
/cc @0xFelix 
This is yet more fallout from DedicatedCPUPlacement being unsupported. IsolateEmulatorThread requires DedicatedCPUPlacement and is removed until we can support the latter.
A TODO is added listing the attributes to add back in once this support lands in KubeVirt.
Fixes #
```release-note
NONE
```
> CX,M,Highperf: Remove IsolateEmulatorThread

- .gitignore
- Makefile
- scripts/functest.sh
- scripts/kubevirt.sh
- scripts/kubevirtci.sh
- scripts/lint.sh
- scripts/sync.sh
/cc @0xFelix 
This PR adds kubevirtci and a simple set of functional tests to the project.
At present these tests are crudely written in bash and only exercise the admission the generated resources *and* the admission of a VirtualMachine referencing these resources. The latter is useful as it exercises the validation codepaths ensuring the common-instancetypes are actually useful.
Fixes #
Draft until https://github.com/kubevirt/common-instancetypes/pull/26 and https://github.com/kubevirt/kubevirt/pull/9103 land allowing the functional tests to pass.
**Release …
> Add kubevirtci deployment support and functional tests

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/legacy/deprecated/deprecated.yaml
- common-instancetypes/instancetypes/legacy/deprecated/kustomization.yaml
- common-instancetypes/instancetypes/legacy/kustomization.yaml
These common-templates based instance types were used to seed the project initially but have since been replaced by the newer hyperscale style resources. This change starts the removal process from the project by marking the generated resources as deprecated with a simple label.
Fixes #
```release-note
The `Server` and `HighPerformance` legacy instance type resources provided by this project are now deprecated ahead of removal in a future release.
```
> Deprecate the legacy instance types

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/hyperscale/cx/base/cx.yaml
- common-instancetypes/instancetypes/hyperscale/cx/sizes/2xlarge/2xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/cx/sizes/4xlarge/4xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/cx/sizes/8xlarge/8xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/cx/sizes/large/large.yaml
- common-instancetypes/instancetypes/hyperscale/cx/sizes/medium/medium.yaml
- common-instancetypes/instancetypes/hyperscale/cx/sizes/xlarge/xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/gn/base/gn.yaml
- common-instancetypes/instancetypes/hyperscale/gn/sizes/2xlarge/2xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/gn/sizes/4xlarge/4xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/gn/sizes/8xlarge/8xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/gn/sizes/xlarge/xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/m/base/m.yaml
- common-instancetypes/instancetypes/hyperscale/m/sizes/2xlarge/2xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/m/sizes/4xlarge/4xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/m/sizes/8xlarge/8xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/m/sizes/large/large.yaml
- common-instancetypes/instancetypes/hyperscale/m/sizes/xlarge/xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/n/sizes/2xlarge/2xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/n/sizes/4xlarge/4xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/n/sizes/8xlarge/8xlarge.yaml
- common-instancetypes/instancetypes/hyperscale/n/sizes/large/large.yaml
- common-instancetypes/instancetypes/hyperscale/n/sizes/medium/medium.yaml
- common-instancetypes/instancetypes/hyperscale/n/sizes/xlarge/xlarge.yaml
The following resource labels have been added to each hyperscale
instance type to aid users searching for a type with specific resources:
* instancetype.kubevirt.io/cpu    - Number of vCPUs
* instancetype.kubevirt.io/memory - Amount of RAM
Additionally the following optional bool labels have also been added to
relevant instance types to help users looking for more specific
resources and features:
* instancetype.kubevirt.io/dedicatedCPUPlacement
* instancetype.kubevirt.io/hugepages
* instancetype.kubevirt.io/isolateEmulatorThread
* instancetype.kubevirt.io/numa
* instancetype.kubevirt.io/gpus
For example:
```
$ ./cluster-up/kubectl.sh get virtualmachineclusterinstancetype -linstancetype.kubevirt.io/hugepages=true
selecting podman as container runtime …
```
> Add resource labels to hyperscale instance types

- .github/workflows/release.yaml
* Replace the annotation with a label
* Avoid merging bundles togther when using yq
* Remove unnecessary exports of env variables
Fixes #
```release-note
NONE
```
> github: Fix bundle version labelling

- scripts/kubevirtci.sh
Fixes #
```release-note
NONE
```
> chore: stop using deprecated cdi-insecure-registries configmap

- Makefile
- scripts/kubevirt.sh
Pin KubeVirt to v1.0.0.
`pre-commit` also cleaned up some whitespace.
Fixes #
```release-note
NONE
```
> [release-0.3] chore: Pin KubeVirt to v1.0.0

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- instancetypes/cx/1/cx1.yaml
- instancetypes/gn/1/gn1.yaml
- instancetypes/m/1/m1.yaml
- instancetypes/o/1/o1.yaml
- instancetypes/u/1/u1.yaml
This should make instance types of a given class and version more discoverable by end users. Given the limitations around labels a new annotation is introduced to store the display name of a given class.
Fixes #75
```release-note
`instancetype.kubevirt.io/{class,version}' are now labels. A new `instancetype.kubevirt.io/displayName` annotation has been introduced containing the full displayable name of an instance type class.
```
> Move instancetype.kubevirt.io/{class,version} to labels

- scripts/functest.sh
`virtctl create vm` defaults `RunStrategy` to `Always` so we can include a simple check to ensure the VM moves to `Ready` as part of our functests.
Fixes #
```release-note
NONE
```
> functests: Wait for VMs to become Ready

- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-preferences-bundle.yaml
- preferences/centos/9_stream/kustomization.yaml
The current cloud images do not support UEFI boot so for now the perferences to enable EFI and secureboot are being removed from the centos.stream9 preference to avoid confusion.
```
$ virt-filesystems -a CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 --all --long --uuid -h
Name      Type       VFS Label MBR Size Parent   UUID
/dev/sda1 filesystem xfs -     -   7.8G -        a2e35d7f-1574-4fc3-aebd-5e60991d3841
/dev/sda1 partition  -   -     83  7.8G /dev/sda -
/dev/sda  device     -   -     -   10G  -        -
```
Fixes #101 …
> centos.stream9: Remove EFI and secureboot support

- .github/workflows/release.yaml
Adds a simple `CHECKSUMS.sha256` file to each release containing `sha256sum` checksums for the released bundles.
See an example release below on my personal repo:
https://github.com/lyarwood/common-instancetypes/releases/tag/v1.3.5
Fixes #
```release-note
`sha256sum` checksums are now provided for each release by a `CHECKSUMS.sha256` file
```
> release: Add sha256sum `CHECKSUMS.sha256` file to release

- preferences/windows/11/requirements/requirements.yaml
Set the minimum required CPUs to two as mandated by the Windows 11 System Requirements.
Fixes #109 
```release-note
Set Windows 11 minimum CPU requirement to two
```
> Fix Windows 11 minimum CPU requirement

- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-preferences-bundle.yaml
- preferences/windows/11_virtio/metadata/metadata.yaml
- preferences/windows/2k19_virtio/metadata/metadata.yaml
The display name "Microsoft Windows 11/2019 (virtio)" containing the "virtio" is more consistent.
The PR sets the display-name of the  windows.11.virtio preference to a more consistent name
Fixes #
```release-note
Adjust display-name of windows.11.virtio and windows.2k19.virtio
```
> preferences: Adjust display-name of windows.11.virtio and windows.2k19.virtio

- scripts/kubevirtci.sh
kubevirtci does not ship its own virtctl binary which is needed for the functional tests. Fix it by downloading the latest virtctl release binary during setup of the kubevirtci cluster.
Fixes #
```release-note
None
```
> fix: Provide virtctl binary for kubevirtci

- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes/preferences/windows/11/metadata/metadata.yaml
- common-instancetypes/preferences/windows/2k19/metadata/metadata.yaml
- common-preferences-bundle.yaml
The display name "Microsoft Windows 11 (virtio)" and "Microsoft Windows Server 2019 (virtio)" containing the "virtio" is more consistent.
Manualy cherry-pick of a5991ebc5cfc8814c783463dfab07543ba8b74df that is necessary due to ordering changes in the generated bundle files.
CONFLICTS:
common-clusterpreferences-bundle.yaml
common-instancetypes-all-bundle.yaml
common-preferences-bundle.yaml
Fixes #
```release-note
Adjust display-name of windows.11.virtio and windows.2k19.virtio
```
> [release-0.3] preferences: Adjust display-name of windows virtio

- preferences/windows/11/kustomization.yaml
Add missing requirements to windows.11 preferences
Fixes #
```release-note
fix: Add missing requirements to windows.11 preferences
```
> fix: Add missing requirements to windows.11 preferences

- scripts/functest.sh
After fixing the missing requirements on windows.11 preferences, they now need at least 2 vCPUs to pass the functional tests.
Fixes #
```release-note
None
```
> fix: Move functests to u1.large instancetypes

- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes/preferences/windows/11/kustomization.yaml
- common-instancetypes/preferences/windows/2k16/kustomization.yaml
- common-preferences-bundle.yaml
- scripts/functest.sh
Add missing requirements to windows.11 and windows.2k16 preferences and move functests to u1.large instancetype.
Manualy cherry-pick of 16096fb1e1507142ebd74d2801e3bc24884e563 and f39e6c5993f1565334c2046f95019875b035b584.
CONFLICTS:
- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-preferences-bundle.yaml
Fixes #
```release-note
fix: Add missing requirements to windows.11 preferences
fix: Add missing requirements to windows.2k16 preferences
```
> [release-0.3] fix: Add missing requirements to windows.11 and windows.2k16 preferences

- preferences/windows/base/kustomization.yaml
Add an explanation why windows preferences have long termination period.
**Which issue(s) this PR fixes**:
Fixes # https://github.com/kubevirt/common-instancetypes/issues/50
```release-note
None
```
> Add a comment about long termination period for Windows

- tests/functests/test_suite_test.go
- tests/go.mod
- tests/go.sum
- tests/vendor/kubevirt.io/qe-tools/LICENSE
- tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
- tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
- tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
- tests/vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
- tests/vendor/modules.txt
This adds the missing junit and polarion reporters to the functional
testsuite and adds support for passing the cluster config in functest with
the -kubeconfig and -master flags.
Fixes #
```release-note
None
```
> Add missing reporters and flags to functests

- Makefile
Randomize the order of functests on each run and be more verbose during running the tests.
Fixes #
```release-note
None
```
> chore: Randomize functests and be more verbose

- scripts/kubevirt.sh
- scripts/kubevirtci.sh
Containerdisks need to be pulled to the local image store before they can be pushed to another remote.
Fixes #
```release-note
None
```
> fix: Pull containerdisks before pushing them

- Makefile
Fix the version of KubeVirt to v1.1.0 and the version of kubevirtci to 2310161449-94f7214.
Fixes #
```release-note
None
```
> chore: Fix KubeVirt and kubevirtci versions

- .github/scripts/build.sh
Set the correct filenames in CHECKSUMS.sha256 during a release so the
checksum file uses the versioned filenames instead.
Fixes #
```release-note
None
```
> fix: Replace names in checksum file during release

- instancetypes/n/1/n1.yaml
The label node-role.kubernetes.io/worker-dpdk is not widely used, therefore the nodeSelector for this label is dropped.
Fixes #
```release-note
The node-role.kubernetes.io/worker-dpdk nodeSelector is removed from the N instancetypes.
```
> chore: Remove nodeselector from N instancetypes

- preferences/windows/10/kustomization.yaml
This is to keep the Windows 10 preference consistent with the Windows 10 template in [common-templates](https://github.com/kubevirt/common-templates/pull/559), also aligning with Windows 2k22 and Windows 11 which also use UEFI with TPM.
**What this PR does / why we need it**: UEFI and TPM enables additional functionalities in Windows
Fixes #
```release-note
Windows 10 preference now boots from UEFI with TPM instead of BIOS
```
> Update Windows 10 preference to allow for boot from UEFI with TPM

- preferences/windows/10/kustomization.yaml
Windows 10 does not strictly require a TPM. A TPM without persistence might even lead to data loss, when encryption keys are lost.
Fixes #
```release-note
Windows 10 preference now boots from UEFI instead of BIOS
```
> fix: Remove TPM from Windows 10 preference

- .gitignore
- image/build_windows_containerdisk.sh
- image/overlays/generic/post-install.ps1
- image/overlays/windows10/autounattend.xml
- image/overlays/windows11/autounattend.xml
- image/overlays/windows2k16/autounattend.xml
- image/overlays/windows2k16/post-install.ps1
- image/overlays/windows2k19/autounattend.xml
- image/overlays/windows2k22/autounattend.xml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
This PR adds the build_windows_containerdisks.sh script, which uses libvirt to run fully automated installations of OSes and packages them as containerdisks. It also adds functional tests for all supported OSes.
The following OSes are supported:
- Windows 10
- Windows 11
- Windows Server 2016
- Windows Server 2019
- Windows Server 2022
Fixes #
```release-note
None
```
> Add Windows functional tests

- image/build_windows_containerdisk.sh
- image/overlays/windows10/autounattend.xml
The windows10 preference in release-0.4 is still using BIOS to boot the VM, so change the test image to reflect that.
Fixes #
```release-note
None
```
> [release-0.4] tests: Move windows10 image back to BIOS boot

- image/build_windows_containerdisk.sh
- image/validationos.Dockerfile
Since ENV variables were chosen as the way forward to decorate images with appropriate default instancetypes and preferences the labels are dropped from images.
Fixes #
```release-note
None
```
> cleanup: Drop labels from images

- preferences/components/tpm/tpm.yaml
- scripts/kubevirt.sh
- scripts/kubevirtci.sh
/cc @0xFelix 
Fixes #168 
https://issues.redhat.com/browse/CNV-39710
```release-note
Persistent TPMs are now provided by the Windows 11 and Windows 2k22 preferences, this requires that the `VMPersistentState` feature gate is enabled and configured correctly.
```
> Windows 11, 2k22: Enable persistent TPMs

- preferences/components/tpm/tpm.yaml
/cc @0xFelix 
/cherry-pick release-1.0
/cherry-pick release-0.4
This reverts commit b9e4cafd321dfb7a5b14e480e98431098363316c.
After initially being against this [1], being won over by a counter argument [2] and then landing this change [3] it has now come to light that the `common-templates` project will be holding off from switching this on until the underlying feature supports RWO storage classes [4]. In order to stay aligned with `common-templates` this PR reverts the change for the time being.
[1] https://github.com/kubevirt/common-instancetypes/pull/167#issuecomment-2022714965
[2] https://github.com/kubevirt/common-instancetypes/issues/168#issuecomment-2042456495
[3] https://github.com/kubevirt/common-instancetypes/pull/167
[4] …
> Revert "Windows 11, 2k22: Enable persistent TPMs"

- preferences/centos/8_stream_dpdk/kustomization.yaml
- preferences/centos/8_stream_dpdk/requirements/kustomization.yaml
- preferences/centos/8_stream_dpdk/requirements/requirements.yaml
- preferences/centos/9_stream_dpdk/kustomization.yaml
- preferences/centos/9_stream_dpdk/requirements/kustomization.yaml
- preferences/centos/9_stream_dpdk/requirements/requirements.yaml
- preferences/fedora/kustomization.yaml
- preferences/rhel/8_dpdk/kustomization.yaml
- preferences/rhel/8_dpdk/requirements/kustomization.yaml
- preferences/rhel/8_dpdk/requirements/requirements.yaml
- preferences/rhel/9_dpdk/kustomization.yaml
- preferences/rhel/9_dpdk/requirements/kustomization.yaml
- preferences/rhel/9_dpdk/requirements/requirements.yaml
/cc @0xFelix 
https://github.com/kubevirt/kubevirt/pull/12180 has highlighted some issues with the interface multi-queue tunable when coupled with `VirtualMachines` exposing only a single socket to the guest.
This PR addresses two sets of preferences where this tunable is used.
* Fedora - We drop use of the tunable to avoid having to require a larger instance type default elsewhere (containerdisks etc).
* CentOS/RHEL DPDK - We enforce a new requirement of 2 vCPUs exposed as sockets and retain the tunable.
Fixes #
```release-note
The Fedora …
```
> Fix use of interface multi-queue within `Fedora` and `RHEL/CentOS DPDK` preferences

- scripts/cri.sh
Rather than having to remember to set this use a sane default while allowing users to turn it off by using an empty string.
Fixes #
```release-note
NONE
```
> scripts: Default COMMON_INSTANCETYPES_CRI to podman

- README.md
- preferences/kustomization.yaml
- preferences/opensuse/kustomization.yaml
- preferences/opensuse/leap/kustomization.yaml
- preferences/opensuse/leap/metadata/kustomization.yaml
- preferences/opensuse/leap/metadata/metadata.yaml
- preferences/opensuse/leap/requirements/kustomization.yaml
- preferences/opensuse/leap/requirements/requirements.yaml
- preferences/opensuse/tumbleweed/kustomization.yaml
- preferences/opensuse/tumbleweed/metadata/kustomization.yaml
- preferences/opensuse/tumbleweed/metadata/metadata.yaml
- preferences/opensuse/tumbleweed/requirements/kustomization.yaml
- preferences/opensuse/tumbleweed/requirements/requirements.yaml
- scripts/cri.sh
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
These are currently unversioned as Tumbleweed is a rolling distro and Leap's requirements align across the supported versions. When this changes we will look into versioned preferences as with other distros like RHEL etc. SLES preferences will be introduced by a future change but should also align with Leap.
Fixes #
```release-note
OpenSUSE Tumbleweed and Leap preferences have been added to the project.
```
> Introduce OpenSUSE Tumbleweed and Leap preferences

- preferences/centos/7/kustomization.yaml
- preferences/centos/8_stream/kustomization.yaml
Fixes #
```release-note
CentOS 7 and CentOS Stream 8 preferences have been deprecated with the recent EOL of the versions and will be removed in a future release of common-instancetypes.
```
> centos.7,centos.stream8: Mark as deprecated with recent EOLs

- scripts/kubevirt.sh
- scripts/kubevirtci.sh
- scripts/sync.sh
/cc @0xFelix 
Kind providers currently expect to be called from the root of the kubevirtci directory. This change supports them and the k8s providers by switching into this directory before returning after each command.
The sync command is also passed the original common-instancetypes directory and now uses the `-k` option of `kubectl apply` to build and apply resources in a single step.
The aim is to then use this support to provide CI coverage for new arm64 based preferences in the near future.
Fixes #
```release-note
NONE
```
> kubevirt: Support kind kubevirtci providers

- tests/unittests/instancetype_test.go
Previously none of the loaded resources were copied into the test resource slices as the associated slices were left as nil and thus the call to copy didn't actually copy anything.
Fixes #
```release-note
NONE
```
> Fix instance type and preference unit tests

- preferences/base/metadata/metadata.yaml
- preferences/windows/base/metadata/metadata.yaml
/cc @0xFelix 
/cherry-pick release-1.0
This annotation while not defined in the KubeVirt API reference is used by downstream consumers, most notably the OpenShift Console. This commit brings us in line with common-templates where this annotation is set on the VirtualMachine.
https://github.com/kubevirt/common-templates/blob/c0e482da8195f2fd45a0e19d8a4ee17f66a1d4f7/templates/windows10.tpl.yaml#L97
Fixes #
```release-note
`vm.kubevirt.io/os` is now set as an annotation on resulting `VirtualMachineInstances` using preferences provided by the …
```
> preferences: Set vm.kubevirt.io/os within eventual VMI

- README.md
- image/build_windows_containerdisk.sh
- image/validationos.Dockerfile
- instancetypes/u/1/sizes.yaml
- tests/functests/instancetype_test.go
Windows 11 has minimum requirements of 2 vCPUs and 4Gi of memory. To better align with these requirements a new u1.2xmedium size is introduced.
This is used within our functional tests replacing the larger u1.large instance type that provided 8Gi of memory.
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
(cherry picked from commit 42ba37814d8d2356fe07e0d9b6476fb73a7be05d)
Fixes #
```release-note
A new `u1.2xmedium` instance type is now provided to better align with the minimum requirements of 2 vCPUs and 4Gi of RAM for Windows 11
```
> [release-0.4] u1.2xmedium: Add size to better align with Windows requirements

- DEVELOPMENT.md
- Makefile
- scripts/deploy-kubevirt-and-cdi.sh
This tasks are helpful when working wieh an external Kubernetes cluster.
The 'deploy' task installs the bundels and their dependencies, whilw the 'functest' task runs the function tests against the cluster.
No issue writen
The file `deploy-kubevirt-and-cdi` is very similar to the one in the ssp-operator repository. The plan is to update it in the other repository if the one there gets merged.
```release-note NONE
```
> feat: deploy and functest make tasks

- scripts/schema.sh
The recommended openapi2jsonlibrary is incompatible with s390x and outdated since 2019. Consider updating to a newer version released in 2023 for seamless functionality.
**What this PR does / why we need it**: enables s390x
Fixes #
```release-note NONE
```
> fix: openapi2jsonlibrary incompatibility on s390x

- preferences/components/cpu-topology-spread/cpu-topology-spread.yaml
- preferences/rhel/8_dpdk/kustomization.yaml
- preferences/rhel/9_dpdk/kustomization.yaml
This allows for topologies like:
8 vCPUS -> 1 Socket, 4 Cores, 2 Threads
16 vCPUs -> 2 Sockets, 4 Cores, 2 Threads
[...]
Fixes #
```release-note
Spread vCPUs across SocketsCoresThreads in DPDK preferences
```
> feat(dpdk): Spread vCPUs across SocketsCoresThreads

- image/Dockerfile
Update common-instancetypes-builder to use Fedora 40 so golang 1.22 becomes available.
Fixes #
```release-note
None
```
> chore: Update common-instancetypes-builder to use Fedora 40

- tests/functests/instancetype_test.go
Introduce separate tests for insufficient cpu or memory in the functional tests for preference requirements.
Fixes #
```release-note
None
```
> fix(functests): Test rejection on insufficient resources separately

- instancetypes/cx/1/sizes.yaml
- instancetypes/gn/1/sizes.yaml
- instancetypes/m/1/sizes.yaml
- instancetypes/n/1/sizes.yaml
- instancetypes/o/1/sizes.yaml
- instancetypes/rt/1/sizes.yaml
- instancetypes/u/1/sizes.yaml
- tests/unittests/instancetype_test.go
Some additional metadata to help users search through the available resources in an environment.
This label could also be used by admins when extending or customising common-instancetypes with Kustomize through a labelSelector.
Fixes #
```release-note
All instance types now provide a `instancetype.kubevirt.io/size` label denoting the size of the resource as also encoded in the name.
```
> Add instancetype.kubevirt.io/size to all instance types

- instancetypes/gn/1/gn1.yaml
/cc @0xFelix 
/cc @davidvossel 
/kind deprecation
This class doesn't really make any sense given the very inflexible nature of hard coding the GPU device within the instance type.
Users should simply provide their own GPU deviceName within the VM and use the universal u1 class of instance types for vCPUs and memory.
Fixes #
```release-note
The `gn1` class of instance types has been deprecated ahead of removal in a future release, users should manually define their required GPUs in their VM while using the `u1` universal class for vCPU and …
```
> gn: Deprecate GPU NVIDIA class of instance types

- Makefile
- preferences/components/efi-persisted/efi.yaml
- preferences/components/efi-persisted/kustomization.yaml
- preferences/components/secureboot/secureboot.yaml
- preferences/components/tpm/tpm.yaml
- preferences/windows/11/kustomization.yaml
- preferences/windows/2k22/kustomization.yaml
- scripts/cri.sh
- scripts/schema.sh
- scripts/validate.sh
Manual backport of #182 
Fixes #
```release-note
Persistent EFI and TPM are now provided by the Windows 11 and Windows 2k22 preferences
```
> [release-1.1] Windows 11, 2k22: Enable persistent TPMs & EFI

- preferences/rhel/10/amd64/kustomization.yaml
The latest guest images can now boot with secure boot enabled so reflect this in the base amd64 preference.
Fixes #
```release-note
The `rhel.10` preference now enables secureboot
```
> rhel.10: Enable secureboot

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
some Windows images require more time to download image.
This commit adds new flag windows-ready-timeout, which
will allow user to set higher timeout only for Windows VMs.
All other OS distributions will use default timeout.
```
NONE
```
> chore: Add flag for setting timeout for creating windows vms

- scripts/generate.sh
While testing in a local environment, I discovered that the command git describe --tags fails, which in turn causes the generation of common instance types to fail.
To address this issue, a default value of "noversion" will be assigned to the variable in the event that the command fails.
**What this PR does / why we need it**: s390x enablement
Fixes #
```release-note
NONE
```
> fix: set default version when git describe --tags fails

- Makefile
The sync.sh script requires the definition of a BASEDIR variable to apply the types and preferences.
**What this PR does / why we need it**: s390x enablement
Fixes #
```release-note
NONE
```
> fix: deployment to external cluster

- preferences/centos/8_stream_dpdk/requirements/requirements.yaml
- preferences/centos/9_stream_dpdk/requirements/requirements.yaml
- preferences/rhel/8_dpdk/requirements/requirements.yaml
- preferences/rhel/9_dpdk/requirements/requirements.yaml
These preferences actually require at least 8 vCPUs through their use of
a SocketsCoresThreads spread ratio of 4, mapping to 1 socket, 4 cores
and 2 threads that in turn needs 8 vCPUs [1].
[1] https://kubevirt.io/user-guide/user_workloads/instancetypes/#spreadoptions
Fixes #
```release-note
NONE
```
> centos, rhel: Fix DPDK preference requirements

- Makefile
Without this podman will fail with the following error:
```sh
$ export COMMON_INSTANCETYPES_CRI=podman
$ make
scripts/cri.sh "scripts/lint.sh"
Error: parsing reference "quay.io/kubevirtci/common-instancetypes-builder:v20241017-30aa54a ": invalid reference format make: *** [Makefile:40: lint] Error 125
```
Fixes #
```release-note
NONE
```
> Makefile: Remove whitespace from COMMON_INSTANCETYPES_IMAGE_TAG

- scripts/kubevirt.sh
- scripts/kubevirtci.sh
- tests/functests/instancetype_test.go
$subject, additionally this PR also removes the use of the now deprecated `Running` field by our functional test VMs.
Fixes #
```release-note
NONE
```
> Disable common instancetypes deployment by virt-operator

- Makefile
- preferences/components/efi-persisted/efi.yaml
- preferences/components/efi-persisted/kustomization.yaml
- preferences/components/efi/efi.yaml
- preferences/components/efi/kustomization.yaml
- preferences/components/secureboot/secureboot.yaml
- preferences/components/tpm/tpm.yaml
- preferences/windows/11/kustomization.yaml
- preferences/windows/2k22/kustomization.yaml
- scripts/cri.sh
- scripts/schema.sh
- scripts/validate.sh
Manual backport of https://github.com/kubevirt/common-instancetypes/pull/247
This includes 7a710bbba409979941f787c61a551bd90630d34e to resolve a conflict
Fixes #
```release-note
Persistent EFI and TPM are now provided by the Windows 11 and Windows 2k22 preferences
```
> [release-1.0] Windows 11, 2k22: Enable persistent TPMs & EFI

- scripts/kubevirt.sh
- scripts/kubevirtci.sh
/cherry-pick release-1.2
Fixes #
```release-note
NONE
```
> Ensure `commonInstancetypesDeployment` is disabled, wait for resources to be deleted and stop using depreacted FGs 

- tests/functests/instancetype_test.go
**What this PR does / why we need it**: s390x enablement
Fixes #
```release-note
NONE
```
> feat: Disable Windows guest tests on architectures other than amd64

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
some Windows images require more time to download image. This commit adds new flag windows-ready-timeout, which will allow user to set higher timeout only for Windows VMs. All other OS distributions will use default timeout.
Fixes #
```release-note
NONE
```
> [release-1.0] chore: Add flag for setting timeout for creating windows vms

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
some Windows images require more time to download image. This commit adds new flag windows-ready-timeout, which will allow user to set higher timeout only for Windows VMs. All other OS distributions will use default timeout.
Fixes #
```release-note
NONE
```
> [release-1.1] chore: Add flag for setting timeout for creating windows vms

- preferences/rhel/9_realtime/kustomization.yaml
- preferences/rhel/9_realtime/requirements/kustomization.yaml
- preferences/rhel/9_realtime/requirements/requirements.yaml
Add missing requirements into rhel.9.realtime preference.
The preference is using an empty `spread` cpu topology option which defaults to `2`, this means we should require at least 2 cpu cores for the preference 
**Which issue(s) this PR fixes**
Blocks #287 
```release-note
NONE
```
> add requirements into rhel.9.realtime preference

- tests/functests/instancetype_test.go
- Renamed test `[test_id:10737] can be created when enough resources are provided` to `[test_id:TODO] verifies all preferences have at least one compatible instance type`
- Added test to create an instance type from the preference requirements and create a VM from the created instance type.
This will help verify the VM can be created using the preference requirements provided, especially important for cases when `spread` cpu topology is used.
The old test naming wasn't expressing it's intention.
```release-note
NONE
```
> vm spec will use the preference requirements in vm creation test

- preferences/fedora/amd64/kustomization.yaml
- preferences/fedora/arm64/kustomization.yaml
- preferences/fedora/s390x/kustomization.yaml
The `fedora` preference is the only plain OS level preference shipped with interface multiqueue enabled. The only other preferences that enable this are `rhel.8.dpdk`, `rhel.9.dpdk` and `rhel.9.realtime`.
This is an issue as it essentially blocks vCPU hot plug when using the `fedora` preference, always requiring a restart to plug new vCPUs as sockets. To avoid this interface multiqueue is removed from the `fedora` preference.
Fixes #
```release-note
`preferredNetworkInterfaceMultiQueue` is no longer enabled by the `fedora` preference
```
> fedora: Remove use of interface multiqueue

- image/Dockerfile
Bump the builder image to Fedora 41 to get a newer golang.
Fixes #
```release-note
None
```
> chore(builder): Bump to Fedora 41

- image/Dockerfile
/cc @0xFelix 
To do this we switch over to the currently Fedora 41 based golang image provided
by kubevirtci and use the GIMME_GO_VERSION ENV variable to request a
specific version of golang.
This should allow us to bump the version when required in the future
causing the post submit job to fire rebuilding the actual builder image.
Fixes #
```release-note
NONE
```
> image: Request a specific golang version in the builder Dockerfile

- README.md
- docs/labels.md
- preferences/components/diskbus-scsi/diskbus-scsi.yaml
- preferences/components/diskbus-scsi/kustomization.yaml
- preferences/components/interfacemodel-e1000/e1000.yaml
- preferences/components/interfacemodel-e1000/kustomization.yaml
- preferences/kustomization.yaml
- preferences/legacy/kustomization.yaml
- preferences/legacy/metadata/kustomization.yaml
- preferences/legacy/metadata/metadata.yaml
- preferences/linux-efi/kustomization.yaml
- preferences/linux-efi/metadata/kustomization.yaml
- preferences/linux-efi/metadata/metadata.yaml
- preferences/linux/kustomization.yaml
- preferences/linux/metadata/kustomization.yaml
- preferences/linux/metadata/metadata.yaml
- tests/functests/instancetype_test.go
It adds a generic linux preferences used for non-supported linux guest and a legacy SO agnostic preference.
These preferences may be used directly as a baseline for onboarding other specific distribution preferences. It helps to avoid duplicating the same basic preferences along all specific distribution preferences.
Added preferences are:
* linux-efi: This preference requests: virtio disk, virtio interfaces, rng and secureboot EFI.
* linux-bios: This preference requests: virtio disk, virtio interfaces, rng and BIOS (default option).
* legacy: This preference requests: scsi disk and e1000 interfaces.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
> Add generic linux distribution and legacy preference

- tests/unittests/instancetype_test.go
- tests/unittests/test_suite_test.go
Downstream vendors can obviously change the value of this label and as the unit tests currently run against the generated bundle we need to accommodate this fact in our unit tests.
This change adds a simple flag to allow anyone running the unit tests downstream to provide their own expected value for the vendor label.
Fixes #
```release-note
NONE
```
> tests: Add flag for expectedVendor to accommodate downstream modifications

- preferences/debian/kustomization.yaml
- tests/functests/instancetype_test.go
In https://github.com/kubevirt/common-instancetypes/pull/331 we missed out to include `requirements` to Debian preferences. Moreover, due to the fact that in https://github.com/kubevirt/common-instancetypes/pull/322 we included logic to avoid testing preferences without `requirements`, Debian preference wasn't being tested unintentionally.
Fixes #
```release-note
None
```
> Add Debian requirements and avoid skip testing unintended preferences

- Makefile
For example this allows a different expected vendor string to be provided to the unit tests:
```
$ UNITTEST_EXTRA_ARGS="--expected-vendor=no.com" make test
```
Fixes #
```release-note
NONE
```
> chore(tests): Wire up UNITTEST_EXTRA_ARGS

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
This adds the preference-arch flag which allows to specify the architecture to test preferences for. It defaults to the architecture of the first node of the test cluster. Previously preferences were always tested for the arch of the host running the test binary.
Fixes #
```release-note
None
```
> functests: Allow to specify arch to test preferences for

- preferences/alpine/kustomization.yaml
- preferences/centos/10_stream/kustomization.yaml
- preferences/centos/9_stream/kustomization.yaml
- preferences/centos/base/kustomization.yaml
- preferences/cirros/kustomization.yaml
- preferences/fedora/amd64/kustomization.yaml
- preferences/fedora/arm64/kustomization.yaml
- preferences/fedora/s390x/kustomization.yaml
- preferences/opensuse/leap/kustomization.yaml
- preferences/opensuse/tumbleweed/kustomization.yaml
- preferences/rhel/10/amd64/kustomization.yaml
- preferences/rhel/10/arm64/kustomization.yaml
- preferences/rhel/9/amd64/kustomization.yaml
- preferences/rhel/9/arm64/kustomization.yaml
- preferences/rhel/base/kustomization.yaml
- preferences/sles/kustomization.yaml
- preferences/ubuntu/kustomization.yaml
It replaces the use of `base` by `linux` preference where possible. It helps to keep all the common components, i.e., virtio disk, virtio interfaces and rng of different preferences in one single place. Moreover, the common components of preferences have been dropped. Additionally, as consequence, some preferences now use `rng`.
Fixes # [CNV-57428](https://issues.redhat.com/browse/CNV-57428)
```release-note
None
```
> chore(preferences): Replace usage of `base` by `linux` preference

- preferences/legacy/kustomization.yaml
It switches from `scsi` to `sata` as preferred disk bus. This is due to the fact that `scsi` in some guests does not provide drivers for the emulated `scsi` models. Therefore, guests cannot boot, it results in either BSOD or rescue mode.
Fixes #
```release-note
legacy preference: Switched from `scsi` to `sata` as preferred disk bus
```
> chore(preferences): Switch `scsi` to `sata` in legacy

- scripts/kubevirtci.sh
Fixes #
```release-note
NONE
```
> chore: Pin kubevirtci to version used by KUBEVIRT_VERSION

- README.md
- preferences/components/pcihole64/kustomization.yaml
- preferences/components/pcihole64/pcihole64.yaml
- preferences/windows/kustomization.yaml
- preferences/windows/xp/kustomization.yaml
- preferences/windows/xp/metadata/kustomization.yaml
- preferences/windows/xp/metadata/metadata.yaml
- preferences/windows/xp/requirements/kustomization.yaml
- preferences/windows/xp/requirements/requirements.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
It adds `windows.xp` preference, tests and Windows XP container disk flag. Moreover, it adds `unsupported` and `pciHole64` disabler components.
Fixes # [CNV-61449](https://issues.redhat.com/browse/CNV-61449)
```release-note
Added `window.xp` preference
```
> feat(preference): Add Windows XP preference

- README.md
- docs/labels.md
- instancetypes/cx/1/cx1.yaml
- instancetypes/cx/1/sizes.yaml
- instancetypes/m/1/m1.yaml
- instancetypes/m/1/sizes.yaml
- instancetypes/n/1/n1.yaml
- instancetypes/rt/1/rt1.yaml
- tests/unittests/instancetype_test.go
The instancetype.kubevirt.io/hugepages label is also updated to reflect
the size of hugepages requested by the instance type.
n1 and rt1 already provide 1Gi sizes, adding 2Mi sizes for these
specific families is left to a future change if it is ever required.
Fixes #
```release-note
New 1Gi hugepage based sizes affixed with `1gi` have been introduced for the cx1 and m1 instance type families
```
> m1, cx1: Introduce 1Gi hugepage sizes

- README.md
- preferences/components/virtio-transitional/kustomization.yaml
- preferences/components/virtio-transitional/virtio-transitional.yaml
- preferences/kustomization.yaml
- preferences/linux-virtio-transitional/kustomization.yaml
- preferences/linux-virtio-transitional/metadata/kustomization.yaml
- preferences/linux-virtio-transitional/metadata/metadata.yaml
- tests/functests/instancetype_test.go
It adds `linux.virtiotransitional` preference for legacy Linux distributions requiring virtio transitional drivers, e.g., RHEL6.
Moreover, it adds a new component for adding the spec `preferredUseVirtioTransitional`.
Additionally, the `linux.virtiotransitional` has been added to the skip list to avoid the preference for being tested since it does not have `spec.Requirements` field.
Fixes # [CNV-62999](https://issues.redhat.com/browse/CNV-62999)
```release-note
Added `linux.virtiotransitional` preference for Linux requiring virtio …
```
> feat(preference): Add generic virtio transitional linux

- README.md
- preferences/rhel/10/amd64/metadata/metadata.yaml
Manual backport of #396
```release-note
Dropped `Beta` from RHEL 10 preferences.
```
> [release-1.0] chore(preference): Drop `Beta` from RHEL 10

- README.md
- preferences/rhel/10/amd64/metadata/metadata.yaml
- preferences/rhel/10/arm64/metadata/metadata.yaml
Manual backport of https://github.com/kubevirt/common-instancetypes/pull/396
```release-note
Dropped `Beta` from RHEL 10 preferences.
```
> [release-1.2] chore(preference): Drop `Beta` from RHEL 10

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
feat: do not fail functest if the common-instancetype-functest namespace exists
In d/s tests we need to prepopulate some big images before tests run.
That means we have to create the namespace in advance. That is causing
the functest to fail.
This PR adds a condition, that if the namespace already exists, do not
fail
feat: set pull policy for container disks in func tests
To be able to prepopulate the images, the tests need to set
pullIfNotPresent pull policy to the container disk.
```
NONE
```
> feat: e2e tests adjustments

- .golangci.yml
- Makefile
- image/Dockerfile
- tests/functests/instancetype_test.go
- tests/go.mod
- tests/unittests/instancetype_test.go
- tests/unittests/test_suite_test.go
- Use gofumpt to format test files. This is needed for a future golangci-lint update.
- Bump golangci-lint to v2.2.2 and fix new findings.
- Bump golang image and use go 1.24.5 in the builder image.
- Bump minimum go version in tests/go.mod to 1.24.4 to be in sync with tools/go.mod.
Fixes #
```release-note
None
```
> Bump golangci-lint and golang versions

- instancetypes/cx/1/sizes.yaml
feat: add cpu.maxSockets to cx instance types
Adding cpu.maxSockets will disable hotplugging. Hotplugging might cause problems (requesting more cpus, that KVM might not handle (error: Number of hotpluggable cpus requested exceeds the recommended cpus supported by KVM)).
https://issues.redhat.com/browse/CNV-66903
```release-note
feat: add cpu.maxSockets to cx instance types
```
> feat: add cpu.maxSockets to cx instance types

- README.md
- preferences/windows/2k8/kustomization.yaml
- preferences/windows/2k8/metadata/kustomization.yaml
- preferences/windows/2k8/metadata/metadata.yaml
- preferences/windows/2k8/requirements/kustomization.yaml
- preferences/windows/2k8/requirements/requirements.yaml
- preferences/windows/2k8_virtio/kustomization.yaml
- preferences/windows/2k8_virtio/metadata/kustomization.yaml
- preferences/windows/2k8_virtio/metadata/metadata.yaml
- preferences/windows/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
Manual backport of https://github.com/kubevirt/common-instancetypes/pull/385
Fixes # [CNV-66809](https://issues.redhat.com/browse/CNV-66809)
```release-note
Added `windows.2k8` and windows.2k8.virtio` preferences for Windows Server 2008
```
> [release-1.0] feat(preference): Add Windows Server 2008
