kubevirt/common-instancetypes

- Makefile
- scripts/push_image.sh
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
Fixes #
```release-note
NONE
```
> push_image: Build and push with a consistent tag

- .github/workflows/release.yaml
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
Fixes #
```release-note
NONE
```
> workflow: Fix yamllint errors

- image/Dockerfile
/cc @0xFelix 
This needs to be a separate step in order for our post submit jobs to trigger and build the new image. This then needs to be used by our pre-submit job before adding the use of shellcheck to the lint script.
Fixes #
```release-note
NONE
```
> image: Add shellcheck to the image

- README.md
- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes/preferences/windows/2k22/kustomization.yaml
- common-instancetypes/preferences/windows/2k22_virtio/kustomization.yaml
- common-instancetypes/preferences/windows/kustomization.yaml
- common-preferences-bundle.yaml
Fixes #
```release-note
Preferences for Windows Server 2022 have been introduced.
```
> Add Windows Server 2022 preferences 

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/sizes/micro/micro.yaml
Quick typo fix missed in #1 
/cc @0xFelix 
/cc @ksimon1 
Fixes #
```release-note
NONE
```
> Fix micro size label typo

- scripts/schema.sh
The URL was incorrect.
Fixes #
```release-note
NONE
```
> Fix openapi2jsonschema installation URL

- common-clusterinstancetypes-bundle.yaml
- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/base/VirtualMachineClusterInstancetype.yaml
- common-instancetypes/instancetypes/base/VirtualMachineInstancetype.yaml
- common-instancetypes/preferences/base/VirtualMachineClusterPreference.yaml
- common-instancetypes/preferences/base/VirtualMachinePreference.yaml
- common-preferences-bundle.yaml
Each resource is now labelled with a  `instancetype.kubevirt.io/vendor` of `kubevirt.io` to denote their origin.
Fixes #
```release-note
NONE
```
> Add `kubevirt.io` as the vendor for each resource

- .github/workflows/release.yaml
Add release update task for SSP operator.
Fixes #
```release-note
NONE
```
> github: Add release update task for SSP operator

- common-clusterpreferences-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes/preferences/components/termination-grace-period/kustomization.yaml
- common-instancetypes/preferences/components/termination-grace-period/termination-grace-period.yaml
- common-instancetypes/preferences/windows/base/kustomization.yaml
- common-preferences-bundle.yaml
/hold
Fixes #43
Depends on #44
```release-note
All Windows preferences have had a `preferredTerminationGracePeriodSeconds` of `180` added.
```
> Preferred termination grace period seconds

- OWNERS
Fixes #
```release-note
NONE
```
> OWNERS: Add lyarwood and 0xFelix as reviewers

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/hyperscale/o/base/o.yaml
Fixing a typo
Fixes https://github.com/kubevirt/common-instancetypes/issues/67
None
```release-note
None
```
> Fix type in O series description

- scripts/kubevirt.sh
/hold 
Waiting for https://github.com/kubevirt/project-infra/pull/2855
$subject, to avoid us testing against main/HEAD on this stable branch.
Fixes #
```release-note
NONE
```
> [release-0.3] Pin KubeVirt to v1.0.0-rc.0 until GA

- common-clusterinstancetypes-bundle.yaml
- common-instancetypes-all-bundle.yaml
- common-instancetypes-bundle.yaml
- common-instancetypes/instancetypes/o/sizes/2xlarge/2xlarge.yaml
- common-instancetypes/instancetypes/o/sizes/4xlarge/4xlarge.yaml
- common-instancetypes/instancetypes/o/sizes/8xlarge/8xlarge.yaml
- common-instancetypes/instancetypes/o/sizes/large/large.yaml
- common-instancetypes/instancetypes/o/sizes/medium/medium.yaml
- common-instancetypes/instancetypes/o/sizes/xlarge/xlarge.yaml
$subject, these were missed as the PR introducing them landed alongside the PR introducing the O class.
Fixes #82
```release-note
NONE
```
> fix: Add missing resource labels to O instance types

- scripts/lint.sh
Fixes #
```release-note
NONE
```
> lint: Ensure we exit 1 on failure

- .github/workflows/release.yaml
$subject, avoid a repeat of https://github.com/kubevirt/ssp-operator/pull/631
Fixes #
```release-note
NONE
```
> github: Use main for SSP operator sync PR

- image/Dockerfile
- scripts/push_image.sh
Update the builder image so it builds again and uses the latest versions. Also add a tag for latest.
Fixes #
```release-note
None
```
> chore: Update builder image and tag latest

- preferences/windows/2k16/kustomization.yaml
Add missing requirements to windows.2k16 preferences
Fixes #
```release-note
fix: Add missing requirements to windows.2k16 preferences
```
> fix: Add missing requirements to windows.2k16 preferences

- Makefile
Update the builder image to v20231124-0bd5b70
Fixes #
```release-note
None
```
> chore: Update builder image to v20231124-0bd5b70

- image/Dockerfile
Install tar with dnf which is needed by the golangci-lint Makefile target.
Fixes #
```release-note
None
```
> image: Add tar to image

- preferences/windows/base/kustomization.yaml
- tests/unittests/test_suite_test.go
- Fix line length warning in preferences/windows/base/kustomization.yaml
by introducing a line break.
- Rename TestFunctional to TestUnit in unittests suite
Fixes #
```release-note
None
```
> Cosmetic fixes

- instancetypes/cx/1/cx1.yaml
- instancetypes/gn/1/gn1.yaml
- instancetypes/m/1/m1.yaml
- instancetypes/n/1/n1.yaml
- instancetypes/o/1/o1.yaml
- instancetypes/u/1/u1.yaml
Add labels to instancetypes which suggest appropriate PatternFly icons to show in a UI when displaying instancetypes.
Fixes #39 
```release-note
Add labels suggesting appropriate PatternFly icons to instancetypes
```
> feat: Add pf-icon labels to instancetypes

- Makefile
- image/validationos.Dockerfile
- scripts/kubevirt.sh
- scripts/kubevirtci.sh
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
This adds a functest for the windows.11 preference, which makes use of
the freely available Microsoft Validation OS.
Fixes #
Based on #135 
```release-note
None
```
> feat: Add functest for the windows.11 preference

- tests/functests/instancetype_test.go
Add test ids to functional tests
Fixes #
```release-note
None
```
> chore: Add test ids to functional tests

- scripts/kubevirtci.sh
This allows to use fixed versions of KubeVirt and kubevirtci in scripts/kubevirtci.sh, which is intended to be used by release branches.
Fixes #
```release-note
None
```
> feat: Allow to use fixed versions of KubeVirt and kubevirtci

- image/build_windows_containerdisk.sh
- image/validationos.Dockerfile
Add additional labels to windows containerdisks which carry information like an appropriate instancetype or preference to use with the containerdisk. A third label indicates whether a display is needed for the guest.
Fixes #
```release-note
None
```
> feat: Add labels to windows containerdisks

- README.md
- instancetypes/n/1/sizes.yaml
Add the n1.medium instancetype which still provides 4 guest cpus but only 4Gi of memory.
Fixes #
```release-note
Added the n1.medium instancetype which still provides 4 guest cpus but only 4Gi of memory
```
> feat: Add n1.medium instancetype

- image/validationos.Dockerfile
This parenthesis does not belong there, it was likely added by mistake.
Fixes #
```release-note
None
```
> validationos.Dockerfile: Drop superfluous parenthesis

- image/build_windows_containerdisk.sh
- image/overlays/windows2k16/autounattend.xml
- image/overlays/windows2k19/autounattend.xml
- preferences/windows/2k12/kustomization.yaml
- preferences/windows/2k16/kustomization.yaml
- preferences/windows/2k19/kustomization.yaml
Adopt UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective preferences.
Fixes #
```release-note
Adopted UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective preferences.
```
> Adopt UEFI in Windows 2k12, 2k16 and 2k19

- OWNERS
/cc @0xFelix 
/cc @opokornyy 
All the best and thanks for all of your work!
Fixes #
```release-note
NONE
```
> OWNERS: Remove opokornyy

- OWNERS
/cc @0xFelix 
/cc @codingben 
@codingben any objections to being added once again?
This reverts commit 6c2095a4dad5523aece740e2bae21bdb1c930382.
Fixes #
```release-note
NONE
```
> Revert "Remove 'codingben' from OWNERS"

- scripts/cri.sh
/cc @0xFelix 
Reverts https://github.com/kubevirt/common-instancetypes/pull/189
Fixes #
```release-note
NONE
```
> Revert "scripts: Default COMMON_INSTANCETYPES_CRI to podman"

- README.md
- preferences/kustomization.yaml
- preferences/sles/kustomization.yaml
- preferences/sles/metadata/kustomization.yaml
- preferences/sles/metadata/metadata.yaml
- preferences/sles/requirements/kustomization.yaml
- preferences/sles/requirements/requirements.yaml
- scripts/kubevirt.sh
- scripts/kubevirtci.sh
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
- tests/image/sles.Dockerfile
$subject.
Fixes #
```release-note
A SUSE Linux Enterprise Server (SLES) preference has been added
```
> Add SUSE Linux Enterprise Server (SLES) preference

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
/cc @0xFelix 
Fixes #
```release-note
NONE
```
> ubuntu: Add 24.04 test coverage

- README.md
- docs/labels.md
Adds missing labels documentation.
Fixes #192
```release-note
NONE
```
> docs: Add labels documentation

- tests/functests/instancetype_test.go
/cc @0xFelix 
Fixes #
```release-note
NONE
```
> tests: Add VirtualMachine output on failure

- README.md
- preferences/windows/2k12/kustomization.yaml
- preferences/windows/2k12/metadata/kustomization.yaml
- preferences/windows/2k12/metadata/metadata.yaml
- preferences/windows/2k12/requirements/kustomization.yaml
- preferences/windows/2k12/requirements/requirements.yaml
- preferences/windows/2k12_virtio/kustomization.yaml
- preferences/windows/2k12_virtio/metadata/kustomization.yaml
- preferences/windows/2k12_virtio/metadata/metadata.yaml
- preferences/windows/kustomization.yaml
This reverts commit 42bdccc936181dde0bf6629ef705634fcef7463c.
Fixes #
```release-note
Reverted removal of Windows 2k12 from the available preferences
```
> [release-1.0] Revert "Remove Windows 2k12 template"

- Makefile
- scripts/kubevirt.sh
- scripts/kubevirtci.sh
Pin to KubeVirt 1.3 for testing in release-1.1
Fixes #
```release-note
None
```
> [release-1.1] kubevirt: Pin to KubeVirt 1.3 for testing

- README.md
- instancetypes/rt/1/kustomization.yaml
- instancetypes/rt/1/rt1.yaml
- instancetypes/rt/1/sizes.yaml
- instancetypes/rt/VirtualMachineClusterInstancetype/kustomization.yaml
- instancetypes/rt/VirtualMachineInstancetype/kustomization.yaml
- instancetypes/rt/kustomization.yaml
- preferences/rhel/9_realtime/kustomization.yaml
- preferences/rhel/9_realtime/metadata/kustomization.yaml
- preferences/rhel/9_realtime/metadata/metadata.yaml
- preferences/rhel/9_realtime/realtime/kustomization.yaml
- preferences/rhel/9_realtime/realtime/realtime.yaml
- preferences/rhel/kustomization.yaml
- tests/unittests/instancetype_test.go
/hold
Fixes #
```release-note
Added a realtime instancetype class and the rhel.9.realtime preference that are suited for realtime applications like Oslat.
```
> Introduce Real time instance type class and RHEL 9 real time preference

- README.md
- preferences/rhel/9_realtime/metadata/metadata.yaml
Add a display name override to the rhel.9.realtime preference so it becomes distinguishable.
Fixes #
```release-note
None
```
> fix(rhel.9.realtime): Add display name override

- .github/dependabot.yml
Add dependabot configuration for tests. This updates the dependencies on a weekly basis.
Fixes #
```release-note
None
```
> Add dependabot configuration for tests

- .github/dependabot.yml
Add dependabot configuration for tools. This updates the dependencies on a weekly basis.
Fixes #
```release-note
None
```
> Add dependabot configuration for tools

- README.md
- preferences/centos/10_stream/kustomization.yaml
- preferences/centos/10_stream/metadata/kustomization.yaml
- preferences/centos/10_stream/metadata/metadata.yaml
- preferences/centos/10_stream/requirements/kustomization.yaml
- preferences/centos/10_stream/requirements/requirements.yaml
- preferences/centos/10_stream_desktop/kustomization.yaml
- preferences/centos/kustomization.yaml
- preferences/components/efi/efi.yaml
- preferences/components/efi/kustomization.yaml
- preferences/rhel/10/amd64/kustomization.yaml
- preferences/rhel/10/amd64/metadata/kustomization.yaml
- preferences/rhel/10/amd64/metadata/metadata.yaml
- preferences/rhel/10/amd64/requirements/kustomization.yaml
- preferences/rhel/10/amd64/requirements/requirements.yaml
- preferences/rhel/10/arm64/kustomization.yaml
- preferences/rhel/10/arm64/metadata/kustomization.yaml
- preferences/rhel/10/arm64/metadata/metadata.yaml
- preferences/rhel/10/arm64/requirements/kustomization.yaml
- preferences/rhel/10/arm64/requirements/requirements.yaml
- preferences/rhel/10/kustomization.yaml
- preferences/rhel/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
This adds preferences intended to be used with the RHEL 10 Beta and CentOS 10 Stream.
Functional tests are not added yet because containerdisks for these OSes are not yet available.
Fixes #
```release-note
Added preferences for RHEL 10 Beta and CentOS 10 Stream
```
> Add preferences for RHEL 10 Beta and CentOS 10 Stream

- Makefile
Update common-instancetypes-builder to v20240802-59e70de
Fixes #
```release-note
None
```
> chore: Update common-instancetypes-builder

- preferences/components/cpu-topology-sockets/cpu-topology-sockets.yaml
- preferences/components/cpu-topology-spread-4/cpu-topology-spread-4.yaml
- preferences/components/cpu-topology-spread/cpu-topology-spread.yaml
Fixes #
```release-note
NONE
```
> preferences: Use simple `preferredCPUTopology` constants

- Makefile
- scripts/cri.sh
- scripts/schema.sh
- scripts/validate.sh
We need to use a branch on the older release branches to avoid the need for a KubeVirt release to consume API changes.
Fixes #
```release-note
NONE
```
> makefile: Use a specific branch to generate and validate KubeVirt schema

- README.md
- preferences/windows/2k25/kustomization.yaml
- preferences/windows/2k25/metadata/kustomization.yaml
- preferences/windows/2k25/metadata/metadata.yaml
- preferences/windows/2k25/requirements/kustomization.yaml
- preferences/windows/2k25/requirements/requirements.yaml
- preferences/windows/2k25_virtio/kustomization.yaml
- preferences/windows/2k25_virtio/metadata/kustomization.yaml
- preferences/windows/2k25_virtio/metadata/metadata.yaml
- preferences/windows/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
- tests/scripts/build_windows_containerdisk/build.sh
- tests/scripts/build_windows_containerdisk/overlays/windows2k25/autounattend.xml
These are essentially copies of the `windows.11` preferences at this time and will likely be refined with the full release of the platform.
Fixes #
```release-note
New `windows.2k25` and `windows.2k25.virtio` preferences have been added to the project
```
> Introduce Windows Server 2025 preferences

- Makefile
- scripts/kubevirt.sh
Fixes #
```release-note
NONE
```
> Makefile, release-1.2: Pin to KubeVirt v1.4.0-rc.0 and release-1.4

- README.md
- preferences/fedora/kustomization.yaml
- preferences/fedora/s390x/kustomization.yaml
- preferences/fedora/s390x/metadata/kustomization.yaml
- preferences/fedora/s390x/metadata/metadata.yaml
- tests/functests/instancetype_test.go
Fixes #
**Special notes for your reviewer**: s390x enablement
```release-note
NONE
```
> feat: enable support for Fedora on s390x architecture

- .golangci.yml
- Makefile
- tests/functests/instancetype_test.go
- tests/go.mod
- tools/go.mod
Fixes #
```release-note
NONE
```
> chore(deps): Bump go.mod

- tools/go.mod
- tools/go.sum
- tools/vendor/golang.org/x/net/html/doctype.go
- tools/vendor/golang.org/x/net/html/foreign.go
- tools/vendor/golang.org/x/net/html/parse.go
- tools/vendor/modules.txt
Resolves CVE-2024-45338 while we wait for a new release of github.com/mikefarah/yq/v4.
Fixes #
```release-note
NONE
```
> chore(go.mod): Replace golang.org/x/net v0.32.0 with v0.33.0

- README.md
- preferences/debian/kustomization.yaml
- preferences/debian/metadata/kustomization.yaml
- preferences/debian/metadata/metadata.yaml
- preferences/debian/requirements/kustomization.yaml
- preferences/debian/requirements/requirements.yaml
- preferences/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
It adds a preference intended to be used with Debian linux distributions.
Fixes # [CNV-51711](https://issues.redhat.com/browse/CNV-51711)
```release-note
Added Debian preference.
```
> feat(preferences): Add preference for Debian

- README.md
- preferences/debian/kustomization.yaml
- preferences/debian/metadata/kustomization.yaml
- preferences/debian/metadata/metadata.yaml
- preferences/debian/requirements/kustomization.yaml
- preferences/debian/requirements/requirements.yaml
- preferences/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
Manual backport of PR: https://github.com/kubevirt/common-instancetypes/pull/331
It differs from the original PR by including the following commit https://github.com/kubevirt/common-instancetypes/pull/334/commits/7c04a7a6877093f6a9c3b4351ac3dd32fef7953e, squashed into one single commit.
Fixes # [CNV-51711](https://issues.redhat.com/browse/CNV-51711)
```release-note
Added Debian preference
```
> [release-1.3] feat(prefences): Add preference for Debian

- README.md
- docs/labels.md
- preferences/components/diskbus-scsi/diskbus-scsi.yaml
- preferences/components/diskbus-scsi/kustomization.yaml
- preferences/components/interfacemodel-e1000/e1000.yaml
- preferences/components/interfacemodel-e1000/kustomization.yaml
- preferences/kustomization.yaml
- preferences/legacy/kustomization.yaml
- preferences/legacy/metadata/kustomization.yaml
- preferences/legacy/metadata/metadata.yaml
- preferences/linux-efi/kustomization.yaml
- preferences/linux-efi/metadata/kustomization.yaml
- preferences/linux-efi/metadata/metadata.yaml
- preferences/linux/kustomization.yaml
- preferences/linux/metadata/kustomization.yaml
- preferences/linux/metadata/metadata.yaml
- tests/functests/instancetype_test.go
This is a manual backport of PR: https://github.com/kubevirt/common-instancetypes/pull/322 and this commit https://github.com/kubevirt/common-instancetypes/pull/334/commits/2fad61bb3c21caa019d16ced1dfa84e1115f54df
Fixes #
```release-note
Added generic bios and efi linux distribution and legacy preferences
```
> [release-1.2] Add generic linux distribution and legacy preference

- README.md
- preferences/components/diskbus-scsi/diskbus-scsi.yaml
- preferences/components/diskbus-scsi/kustomization.yaml
- preferences/components/interfacemodel-e1000/e1000.yaml
- preferences/components/interfacemodel-e1000/kustomization.yaml
- preferences/kustomization.yaml
- preferences/legacy/kustomization.yaml
- preferences/legacy/metadata/kustomization.yaml
- preferences/legacy/metadata/metadata.yaml
- preferences/linux-efi/kustomization.yaml
- preferences/linux-efi/metadata/kustomization.yaml
- preferences/linux-efi/metadata/metadata.yaml
- preferences/linux/kustomization.yaml
- preferences/linux/metadata/kustomization.yaml
- preferences/linux/metadata/metadata.yaml
- tests/functests/instancetype_test.go
This is a manual backport of PR: https://github.com/kubevirt/common-instancetypes/pull/322 and this commit https://github.com/kubevirt/common-instancetypes/commit/2fad61bb3c21caa019d16ced1dfa84e1115f54df
Fixes #
```release-note
Added generic bios and efi linux distribution and legacy preferences
```
> [release-1.0] Add generic linux distribution and legacy preference

- scripts/kubevirt.sh
- scripts/kubevirtci.sh
Fixes #362
```release-note
NONE
```
> chore(kubevirtci): Stop deploying NFS

- Makefile
Fixes #
```release-note
NONE
```
> [release-1.2] chore(Makefile): Pin KUBEVIRT_VERSION to v1.4.0

- Makefile
- scripts/kubevirt.sh
- scripts/kubevirtci.sh
This also includes https://github.com/kubevirt/common-instancetypes/pull/363 as this change is now present on the release-1.5 branch of KubeVirt.
Fixes #
```release-note
NONE
```
> [release-1.3] chore(kubevirtci): Pin to KubeVirt v1.5.0

- README.md
- preferences/rhel/10/kustomization.yaml
- preferences/rhel/10/s390x/kustomization.yaml
- preferences/rhel/10/s390x/metadata/kustomization.yaml
- preferences/rhel/10/s390x/metadata/metadata.yaml
- preferences/rhel/10/s390x/requirements/kustomization.yaml
- preferences/rhel/10/s390x/requirements/requirements.yaml
- tests/functests/instancetype_test.go
This adds preferences intended to be used with the RHEL 10 Beta for s390x arch.
Fixes #
```release-note
Added preferences for RHEL 10 Beta for s390x
```
> feat: Add preferences for RHEL 10 Beta s390x

- preferences/base/metadata/metadata.yaml
- preferences/centos/9_stream_dpdk/requirements/requirements.yaml
- preferences/components/cpu-topology-spread/cpu-topology-spread.yaml
- preferences/legacy/metadata/kustomization.yaml
- preferences/rhel/8_dpdk/requirements/requirements.yaml
- preferences/rhel/9_dpdk/requirements/requirements.yaml
- scripts/lint.sh
Fixes #304 
```release-note
NONE
```
> chore(lint): Fix warnings and drop use of relaxed `yamllint` profile

- tests/functests/instancetype_test.go
Drop ssh test in Windows XP.
Fixes #
```release-note
None
```
> chore(test): Drop ssh test in Windows XP

- tools/go.mod
This is required by downstream tooling that expects and uses the full x.y.z toolchain version style string over the shorter x.y language version string.
Fixes #
```release-note
NONE
```
> tools: Use 1.24.4 toolchain version string

- scripts/kubevirtci.sh
Fixes #
```release-note
None
```
> Fix: remove extra ')' in KUBEVIRT_VERSION export

- README.md
- preferences/windows/7/kustomization.yaml
- preferences/windows/7/metadata/kustomization.yaml
- preferences/windows/7/metadata/metadata.yaml
- preferences/windows/7/requirements/kustomization.yaml
- preferences/windows/7/requirements/requirements.yaml
- preferences/windows/7_virtio/kustomization.yaml
- preferences/windows/7_virtio/metadata/kustomization.yaml
- preferences/windows/7_virtio/metadata/metadata.yaml
- preferences/windows/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
Manual backport of https://github.com/kubevirt/common-instancetypes/pull/430
Fixes # [CNV-66809](https://issues.redhat.com/browse/CNV-66809)
```release-note
Added `windows.7` and `windows.7.virtio` preferences for Windows 7
```
>  [release-1.0] feat(preferences): Add Windows 7

- README.md
- preferences/windows/7/kustomization.yaml
- preferences/windows/7/metadata/kustomization.yaml
- preferences/windows/7/metadata/metadata.yaml
- preferences/windows/7/requirements/kustomization.yaml
- preferences/windows/7/requirements/requirements.yaml
- preferences/windows/7_virtio/kustomization.yaml
- preferences/windows/7_virtio/metadata/kustomization.yaml
- preferences/windows/7_virtio/metadata/metadata.yaml
- preferences/windows/kustomization.yaml
- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
Manual backport of https://github.com/kubevirt/common-instancetypes/pull/430
Fixes # [CNV-66808](https://issues.redhat.com/browse/CNV-66808)
```release-note
Added `windows.7` and `windows.7.virtio` preferences for Windows 7
```
>  [release-1.1] feat(preferences): Add Windows 7

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
Add test for Debian 13. This will ensure the `debian` preference is still valid for Debian 13 too.
Fixes # [CNV-68033](https://issues.redhat.com/browse/CNV-68033)
```release-note
None
```
> chore(test): Add functional test for Debian 13

- tests/functests/instancetype_test.go
- tests/functests/test_suite_test.go
Manual backport of https://github.com/kubevirt/common-instancetypes/pull/447
Fixes #
```release-note
None
```
> [release-1.1] chore(test): Add functional test for Debian 13
